apps/entities/urls.py
from django.urls import path
from apps.entities.views import EntityCreateView, EntityListView, EntityUpdateView, EntityDeleteView

app_name = 'entities'
urlpatterns = [
    path("entidades/criar/", EntityCreateView.as_view(), name="entity_create"),
    path("entidades/listar/", EntityListView.as_view(), name="entity_list"),
    path("entidades/editar/<int:pk>/", EntityUpdateView.as_view(), name="entity_update"),
    path("entidades/excluir/<int:pk>/", EntityDeleteView.as_view(), name="entity_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.users.urls'), name='users'),
    path('', include('apps.entities.urls'), name='entities'),
    path('', include('apps.logistics.urls'), name='logistics'),
]

apps/entities/models.py
from django.db import models
from apps.core.models import TenantAwareModel
from django.utils.text import slugify

class Entity(TenantAwareModel):
    choices = {
        'CPF': 'CPF',
        'CNPJ': 'CNPJ',
    }
    name = models.CharField(max_length=100)
    fantasy_name = models.CharField(max_length=100, blank=True, null=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    cpf = models.CharField(max_length=11, unique=True, blank=True, null=True)
    cnpj = models.CharField(max_length=14, unique=True, blank=True, null=True)
    cpforcnpj = models.CharField(max_length=4, choices=choices.items(), default='CNPJ')
    economic_group = models.ForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, related_name='economic_groups')
    is_active = models.BooleanField(default=True)
    is_branch = models.BooleanField(default=False)
    is_system = models.BooleanField(default=False, help_text='Allow access to the entity as system company')

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.cpf:
            self.cpfoucnpj = self.choices['CPF']
        else:
            self.cpfoucnpj = self.choices['CNPJ']
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Entity'
        verbose_name_plural = 'Entities'
        ordering = ['name']

class EntityAddress(TenantAwareModel):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, related_name='entity_addresses')
    country = models.CharField(max_length=100)
    country_code = models.CharField(max_length=5)
    state = models.CharField(max_length=5)
    city = models.CharField(max_length=100)
    city_code = models.CharField(max_length=7)
    district = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    number = models.CharField(max_length=10, blank=True, null=True)
    complement = models.CharField(max_length=100, blank=True, null=True)
    zip_code = models.CharField(max_length=8)
    is_main = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.entity.name} - {self.city} - {self.state}"

class EntityPhone(TenantAwareModel):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, related_name='entity_phones')
    phone = models.CharField(max_length=20)
    is_main = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.entity.name} - {self.phone}"

class PartyRole(models.TextChoices):
    CLIENT = "client", "Client"
    CARRIER = "carrier", "Carrier"
    SENDER  = "sender", "Sender"
    RECEIVER = "receiver", "Receiver"
    WAREHOUSE = "warehouse", "Warehouse"

class Party(TenantAwareModel):
    """
    Representa o papel de uma Entity em um contexto.
    Ex.: Cliente, Fornecedor, Transportadora.
    """
    entity = models.ForeignKey(
        'Entity',
        on_delete=models.PROTECT,
        related_name='parties'
    )
    role = models.CharField(
        max_length=20,
        choices=PartyRole.choices,
        default=PartyRole.CLIENT.value
    )
    alias = models.CharField(max_length=100, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        unique_together = ('entity', 'role')
        verbose_name = 'Party'
        verbose_name_plural = 'Parties'

    def __str__(self):
        return f"{self.entity.name} ({self.role})"

apps/entities/forms.py
from django.forms import ModelForm
from django import forms
from apps.entities.models import Entity
from domain.bootstrap.service_container import get_party_service

class EntityForm(ModelForm):

    def clean(self):
        cleaned_data = super().clean()
        party_service = get_party_service()
        existing_roles = party_service.get_existing_roles()
        selected_roles = []

        for role, translation in existing_roles:
            if cleaned_data.get(role):
                selected_roles.append(role)

        if not selected_roles:
            raise forms.ValidationError("A entidade deve ter pelo menos um papel.")

        for role in selected_roles:
            if not party_service.can_be(entity=self.instance, role=role):
                raise forms.ValidationError(f"A entidade não pode ser um {role}.")

        self.selected_roles = selected_roles
        
        return cleaned_data
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["economic_group"].label_from_instance = (
            lambda obj: f"{obj.id} - {obj.name}"
        )

        party_service = get_party_service()
        existing_roles = party_service.get_existing_roles()
        if self.instance.pk:
            current_roles = self.instance.parties.all()
        else:
            current_roles = []
        for role, translation in existing_roles:
            self.fields[role] = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={"class": "form-check-input"}))
        for party in current_roles:
            self.fields[party.role].initial = True



    class Meta:
        model = Entity
        fields = [
            "name", "cpf", "cnpj", "cpforcnpj",
            "is_active", "is_branch",
            "is_system", "economic_group"
        ]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "cpf": forms.TextInput(attrs={"class": "form-control"}),
            "cnpj": forms.TextInput(attrs={"class": "form-control"}),
            "cpforcnpj": forms.Select(attrs={"class": "form-select"}),

            "is_active": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "is_branch": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "is_system": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "economic_group": forms.Select(attrs={"class": "form-select select2"}),
        }
        

apps/entities/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib import messages
from apps.entities.models import Entity
from apps.entities.forms import EntityForm

class EntityCreateView(CreateView):
    model = Entity
    form_class = EntityForm
    success_url = "/entidades/listar/"

    def form_valid(self, form):
        response = super().form_valid(form)

        from domain.bootstrap.service_container import get_party_service
        party_service = get_party_service()

        party_service.sync_entity_roles(
            self.object,
            form.selected_roles
        )

        messages.success(self.request, 'Entidade criada com sucesso!')
        return response

    def form_invalid(self, form):
        messages.warning(self.request, f'Erro ao criar entidade! {form.errors}')
        return super().form_invalid(form)

class EntityListView(ListView):
    model = Entity
    context_object_name = "entities"
    paginate_by = 15
    def get_queryset(self):
        return Entity.objects.filter(tenant=self.request.tenant)
    
class EntityUpdateView(UpdateView):
    model = Entity
    form_class = EntityForm
    success_url = "/entidades/listar/"

    def form_valid(self, form):
        response = super().form_valid(form)

        from domain.bootstrap.service_container import get_party_service
        party_service = get_party_service()

        party_service.sync_entity_roles(
            self.object,
            form.selected_roles
        )

        messages.success(self.request, 'Entidade atualizada com sucesso!')
        return response

    def form_invalid(self, form):
        messages.warning(self.request, f'Erro ao atualizar entidade! {form.errors}')
        return super().form_invalid(form)
        
class EntityDeleteView(DeleteView):
    model = Entity
    success_url = "/entidades/listar/"

apps/entities/templates/entities/entity_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <script src="{% static 'entities/js/entity_form.js' %}"></script>
{% endblock head %}
{% block content %}
    <div class="container mt-4" style="max-width: 1900px;">
        <h3 class="mb-4">
            {% if object %}
                Editar Entidade
            {% else %}
                Criar Entidade
            {% endif %}
        </h3>
        <form method="post">
            {% csrf_token %}
            <!-- Dados principais -->
            <div class="row mb-3">
                <div class="col-md-12">
                    <label class="form-label">Nome</label>
                    {{ form.name }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-3">
                    <label class="form-label">Grupo econômico</label>
                    {{ form.economic_group }}
                </div>
                <div class="col-md-3">
                    <label class="form-label">Tipo</label>
                    {{ form.cpforcnpj }}
                </div>
                <div class="col-md-3">
                    <label class="form-label">CPF</label>
                    {{ form.cpf }}
                </div>
                <div class="col-md-3">
                    <label class="form-label">CNPJ</label>
                    {{ form.cnpj }}
                </div>
            </div>
            <hr>
            <!-- Flags -->
            <div class="row mb-3">
                <div class="col-md-4 form-check">
                    {{ form.is_active }}
                    <label class="form-check-label">Ativo</label>
                </div>
                <div class="col-md-4 form-check">
                    {{ form.client }}
                    <label class="form-check-label">Cliente</label>
                </div>
                <div class="col-md-4 form-check">
                    {{ form.carrier }}
                    <label class="form-check-label">Transportadora</label>
                </div>
            </div>
            
            <div class="row mb-4">
                <div class="col-md-4 form-check">
                    {{ form.is_branch }}
                    <label class="form-check-label">Filial</label>
                </div>
                <div class="col-md-4 form-check">
                    {{ form.is_system }}
                    <label class="form-check-label">Sistema</label>
                </div>
            </div>
            <div class="d-flex gap-2">
                <button type="submit" class="btn btn-primary">Salvar</button>
                {% comment %} <a href="{% url 'entity-list' %}" class="btn btn-secondary">Cancelar</a> {% endcomment %}
            </div>
        </form>
    </div>
{% endblock content %}

apps/entities/templates/entities/entity_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-4" style="max-width: 1900px;">
        <h3 class="mb-4">Listagem de entidades</h3>
        <a href="{% url 'entities:entity_create' %}"
           class="btn btn-primary mb-4">Adicionar entidade</a>
        <table class="table">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Tipo</th>
                    <th>Ativo</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for entity in entities %}
                    <tr>
                        <td>{{ entity.name }}</td>
                        <td>{{ entity.cpforcnpj }}</td>
                        <td>{{ entity.is_active|yesno:"Sim,Não" }}</td>
                        <td>
                            <a href="{% url 'entities:entity_update' entity.id %}"
                               class="btn btn-warning btn-sm">Editar</a>
                            <a href="{% url 'entities:entity_delete' entity.id %}"
                               class="btn btn-danger btn-sm">Excluir</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if is_paginated %}
            <nav aria-label="Paginação">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Anterior</span>
                        </li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item active">
                                <span class="page-link">{{ num }}</span>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Próxima</span>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
{% endblock content %}